### ISSUE TITLE
[Bug] Critical: After Upgrade to v2.0.0-rc.35, failed to use subtitle to scroll

### ISSUE THREAD

**Issue by lancy6001** [vuepress-theme-hope/vuepress-theme-hope#4057]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Uncaught (in promise) TypeError: scrollPromise is not a function
    at router.options.scrollBehavior (config.js:29:13)
    at vue-router.mjs:3514:25

### Additional context

 This is critical issue
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/59279078/69ac031c-f16f-4e89-8d55-bcac056a82fc)
After click the subtitle, system will scroll to the section, but after upgrade, this will popup issue :
TypeError: scrollPromise is not a function
    at router.options.scrollBehavior (config.js:29:13)
    at vue-router.mjs:3514:25

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/4055
