### ISSUE TITLE
[Bug] ERROR: No loader is configured for ".vue" with vuepress-theme-hope@v2.0.0-beta97

### ISSUE THREAD

**Issue by NicolasThierion** [vuepress-theme-hope/vuepress-theme-hope#2190]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

I want to customize theme-hope with *component aliases* as described in [this page](https://vuepress-theme-hope.github.io/v2/cookbook/advanced/replace.html#replace-components)

- Things used to work with **vuepress-next@v2.0.0-beta49** + **vuepress-theme-hope@v2.0.0-beta.86**.
- I updated today to **vuepress-next@v2.0.0-beta51** + **vuepress-theme-hope@v2.0.0-beta97**, and it throws the following error: 
```
error while updating dependencies:
Error: Build failed with 1 error:
node_modules/vuepress-theme-hope/lib/client/components/HomePage.js:4:25: ERROR: No loader is configured for ".vue" files: src/components/HomeFeatures.vue
    at failureErrorWithLog (/tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:1624:15)
    at /tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:1264:7)
    at /tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:1377:14
    at /tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/tmp/test/node_modules/vite/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:390:28)
```

- I tried to narrow down the version where the issue appeared, and it seems to break since  **vuepress-next@v2.0.0-beta50** + **vuepress-theme-hope@v2.0.0-beta93**.

You can find a minimal reproduction on [this repository](https://github.com/NicolasThierion/vuepress-theme-hope-component-alias)
 - [`main` branch](https://github.com/NicolasThierion/vuepress-theme-hope-component-alias) = **vuepress-next@v2.0.0-beta51** + **vuepress-theme-hope@v2.0.0-beta97**.
 - [`old`](https://github.com/NicolasThierion/vuepress-theme-hope-component-alias/tree/old) branch = **vuepress-next@v2.0.0-beta49** + **vuepress-theme-hope@v2.0.0-beta90** works.
 
 I'm not sure if the problem comes from `vuepress` itself of `vuepress-theme-hope`, but with `themeDefault()` from `vuepress`, I had no issues with setting component aliases.
 
 Thank you for your help, and congratulations for all the work.

**Comment by Mister-Hope** [comment]
Could you please try creating a simple HomeFeatures.js wrapper?

```js
import HomeFeatures from './HomeFeatures.vue';

export default HomeFeatures;
```

And see if it works?

**Comment by NicolasThierion** [comment]
Indeed, works like a charm!

I'm pretty bad with vuejs, and I didn't event know this was possible.
This workaround is perfect for me, but maybe this need more attention in the future.

Thank you again !

**Comment by Mister-Hope** [comment]
I do think documentation needs some update here, so I will leave this open
